name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    
      with:
        flutter-version: '3.10.1'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./flutter

    - name: Update dependencies
      run: flutter pub upgrade
      working-directory: ./flutter


    - name: Build apk
      run: flutter build apk
      working-directory: ./flutter


    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./flutter/build/app/outputs/flutter-apk/app-release.apk
