name: Flutter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.1'
    - run: flutter pub get
    - run: flutter build apk
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: silversabres.${{ github.sha }}.android
        path: build/app/outputs/flutter-apk/app-release.apk
    
  build_ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.1'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: silversabres.${{ github.sha }}.ios
        path: build/ios/iphoneos/Runner.app
